routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/form', 'ClientController@form');
Route::get('/get-client-register', 'FormController@GetClientRegister');
Route::get('/get-client-login', 'FormController@GetClientLogin');
Route::post('/client-register', 'FormController@ClientRegister');
Route::post('/client-login', 'FormController@ClientLogin');

Route::group(['middleware' => 'auth:web'],function(){
    Route::resource('/all-rooms', 'RoomController');
});

Route::group(['middleware' => 'auth:client'],function(){
    Route::get('/home-client', 'FormController@home');
    Route::post('/client-logout', 'FormController@ClientLogout');
    Route::get('/rooms', 'BookingController@index');
    Route::post('/room/book', 'BookingController@store');
    Route::get('/my_bookings', 'BookingController@my_bookings');
    Route::get('/room/{id}/view', 'BookingController@show');
    Route::get('/room/{id}/book', 'BookingController@create');
});

resources/views/admin/add-room.blade.php
@extends('layouts.app')

@section('content')
    <a href="/all-rooms" class="btn btn-outline-dark mb-2 mt-2">Back</a>
    <div class="card card-body bg-white text-center">
        {!! Form::open(['action' => 'RoomController@store','method' => 'POST' , 'enctype' => 'multipart/form-data']) !!}
        <div class="form-group">
            {{Form::label('name','Name')}}
            {{Form::text('name','',['class' => 'form-control','placeholder' => 'Name'])}}
        </div>
        <div class="form-group">
            {{Form::label('floor','Floor')}}
            {{Form::text('floor','',[ 'class' => 'form-control','placeholder' => 'Floor'])}}
        </div>
        <div class="form-group">
            {{Form::label('building','Building')}}
            {{Form::text('building','',[ 'class' => 'form-control','placeholder' => 'Building'])}}
        </div>
        <div class="form-group">
            {{Form::file('image')}}
        </div>
        {{Form::submit('submit',['class' => 'btn btn-primary'])}}
        {!! Form::close() !!}
    </div>
@endsection

resources/views/admin/edit-room.blade.php
@extends('layouts.app')

@section('content')
    <a href="/all-rooms" class="btn btn-outline-dark mb-2 mt-2">Back</a>
    <div class="card card-body bg-white text-center">
        {!! Form::open(['action' => ['RoomController@update' , $room->id],'method' => 'POST','enctype' => 'multipart/form-data']) !!}
        <div class="form-group">
            {{Form::label('name','Name')}}
            {{Form::text('name',$room->name,['class' => 'form-control','placeholder' => 'Name'])}}
        </div>
        <div class="form-group">
            {{Form::label('floor','Floor')}}
            {{Form::text('floor',$room->floor,[ 'class' => 'form-control','placeholder' => 'Floor'])}}
        </div>
        <div class="form-group">
            {{Form::label('building','Building')}}
            {{Form::text('building',$room->building,[ 'class' => 'form-control','placeholder' => 'Building'])}}
        </div>
        <div class="form-group">
            {{Form::file('image')}}
        </div>
        {{Form::hidden('_method','PUT')}}
        {{Form::submit('submit',['class' => 'btn btn-primary'])}}
        {!! Form::close() !!}
    </div>
@endsection

resources/views/admin/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Home</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <div class="text-center">
                        <h2>Welcome To Admin Homepage</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/rooms.blade.php
@extends('layouts.app')

@section('content')
<!-- Main content -->
<section class="content">
@include('flash::message')
<!-- Default box -->
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title mt-2">Rooms</h3>
            <a href="{{action('RoomController@create')}}" class="btn btn-outline-dark float-right m-2">Create Room</a>
        </div>
        <div class="box-body">
            @if(count([$rooms]))
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Room Name</th>
                            <th>Floor</th>
                            <th>Building</th>
                            <th>Image</th>
                            <th>Edit</th>
                            <th class="text-center">Delete</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($rooms as $room)
                            <tr>
                                <td>{{$loop->iteration}}</td>
                                <td>{{$room->name}}</td>
                                <td>{{$room->floor}}</td>
                                <td>{{$room->building}}</td>
                                <td>
                                    <img src="{{($room->roomImage())}}" alt="" style="height: 100px;">
                                </td>
                                <td class="text-center">
                                    <a href="{{url(route('all-rooms.edit', $room->id))}}" class=" btn btn-success btn-xs">
                                        <i class="fa fa-edit">Edit</i>
                                    </a>
                                </td>
                                <td class="text-center">
                                    {!! Form::open([
                                        'action' => ['RoomController@destroy',$room->id],
                                        'method' => 'delete'
                                    ]) !!}
                                    <button type="submit" class="delete_link btn btn-danger btn-xs">
                                        <i class="fa fa-trash-o">
                                            Delete
                                        </i></button>

                                    {!! Form::close() !!}
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            @else

                <div class="alert alert-danger" role="alert">
                    No Data
                </div>
            @endif
        </div>
    </div>
    <!-- /.box -->

</section>
<!-- /.content -->
@endsection